server:
  port: 8081

spring:
  profiles:
    default: prod
  application:
    name: auth-service
  config:
    import: 'optional:configserver:http://localhost:8888'
  cloud:
    config:
      fail-fast: true
