server:
  port: 8080
  forward-headers-strategy: framework
  address: 0.0.0.0

spring:
  profiles:
    default: prod
  application:
    name: api-gateway
  config:
    import: 'optional:configserver:http://config:8888'
  cloud:
    config:
      fail-fast: true





