server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  instance:
    #    lease-renewal-interval-in-seconds: 1
    #    lease-expiration-duration-in-seconds: 1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    #    registry-fetch-interval-seconds: 1
    register-with-eureka: true

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework.web: DEBUG

#  cloud:
#    gateway:
#      routes:
#        - id: profile-service-route
#          uri: lb://profile-service
#          predicates:
#            - Path=/profiles/**
#          filters:
#            - name: JwtAuthenticationFilter
#
#        - id: auth-service-route
#          uri: lb://auth-service
#          predicates:
#            - Path=/auth/**
#
#        - id: auth-api-service-route
#          uri: lb://auth-service
#          predicates:
#            - Path=/api/users/**


