server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  instance:
    #    lease-renewal-interval-in-seconds: 1
    #    lease-expiration-duration-in-seconds: 1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    #    registry-fetch-interval-seconds: 1
    register-with-eureka: true

logging:
  level:
    root: info




