server:
  port: 0

spring:
  application:
    name: post-service
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yml
  config:
    import: 'optional:configserver:http://localhost:8888'
  cloud:
    config:
      fail-fast: true
  mvc:
    format:
      date: iso
  datasource:
    url: jdbc:postgresql://localhost:5433/postdb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true

logging:
  level:
    root: info

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
