server:
  port: 8085

spring:
  profiles:
    default: prod
  application:
    name: post-service
  config:
    import: 'configserver:http://localhost:8888'
  cloud:
    config:
      fail-fast: true
  jpa:
    properties:
      hibernate:
        show_sql: true
