server:
  port: 8084

spring:
  profiles:
    default: prod
  application:
    name: subscribe-service
  config:
    import: 'optional:configserver:http://localhost:8888'
  cloud:
    config:
      fail-fast: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
