server:
  port: 8084
  address: 0.0.0.0

spring:
  profiles:
    default: prod
  application:
    name: subscribe-service
  config:
    import: 'optional:configserver:http://config:8888'
  cloud:
    config:
      fail-fast: true

