server:
  port: 8083
  address: 0.0.0.0

spring:
  profiles:
    default: prod
  application:
    name: email-notification-service
  config:
    import: 'optional:configserver:http://config:8888'
  cloud:
    config:
      fail-fast: true
  mail:
    password: tvwpcaemuctkzaqb


