server:
  port: 8761
  address: 0.0.0.0

spring:
  profiles:
    default: prod
  application:
    name: eureka-server
  config:
    import: 'optional:configserver:http://localhost:8888'
  cloud:
    config:
      fail-fast: true


